from portScanner.cli import main as main
from portScanner.scanner import DEFAULT_DELAY as DEFAULT_DELAY
from portScanner.scanner import DEFAULT_PORT_END as DEFAULT_PORT_END
from portScanner.scanner import DEFAULT_PORT_START as DEFAULT_PORT_START
from portScanner.scanner import DEFAULT_SCAN_TIMEOUT as DEFAULT_SCAN_TIMEOUT
from portScanner.scanner import DEFAULT_THREADS as DEFAULT_THREADS
from portScanner.scanner import DEFAULT_TIMEOUT as DEFAULT_TIMEOUT
from portScanner.scanner import SERVICE_PORTS as SERVICE_PORTS
from portScanner.scanner import PortScanner as PortScanner
